my_string=input('здраствуте как Ваше ничего ? ')
print(my_string)
print(len(my_string))
print(my_string .upper())
print(my_string .lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])
